POST http://localhost:3001/api/notes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InllbGlkcmljIiwiaWQiOiI2OGY5ZTMxYjNjODM2MGY0YmY4ODRkZGYiLCJpYXQiOjE3NjEyOTcyMjB9.wqhzmfRcDHpvMwtbBt2YtnuqpLFAkQHTP2Awr9Quw18

{
  "content": "Yelidric create this important note",
  "important": true
}

###
POST http://localhost:3001/api/notes
Content-Type: application/json

{
  "important": true
}